name: test-ext-prs

on:
  pull_request_target:
    branches:
      - main

permissions:
  contents: read

jobs:
  authorize:
    environment:
      ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository && 'external' || 'internal' }}
    runs-on: ubuntu-latest
    steps:
      - run: true

  test:
    needs: authorize
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha || github.ref }}
      - name: Print git HEAD
        run: git log -1 --pretty=oneline
      - name: Print REPO_SECRET
        run: printenv REPO_SECRET 
        env:
          REPO_SECRET: ${{ secrets.REPO_SECRET }}
